config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :events, except: %i[edit update destroy]
  resources :attendances, only: %i[show]
  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
require 'date'
class Event < ApplicationRecord
  scope :past, -> { where('event_date < ?', Date.current) }
  scope :upcoming, -> { where('event_date >= ?', Date.current) }

  validates :description, :location, :event_date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: 'attended_event_id'
  has_many :attendees, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def require_login
    return if helpers.user_sign_in?

    respond_to do |format|
      format.html { redirect_to new_session_path, notice: 'You must be logged in to access this section' }
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.attendees << helpers.current_user
        format.html { redirect_to user_path(session[:user_id]), notice: 'successfully attended to the event' }
      else
        format.html { redirect_to events_path, notice: 'Event not available' }
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @past_events = Event.past.all
    @upcoming_events = Event.upcoming.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = helpers.current_user.created_events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to user_path(@event.creator_id), notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:description, :location, :event_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = authenticate(session_params)

    respond_to do |format|
      if @user
        session[:user_name] = @user.username
        session[:user_id] = @user.id
        format.html { redirect_to user_path(@user.id), notice: 'successfully logged in' }
      else
        format.html { redirect_to new_session_path, notice: 'User not found!' }
      end
    end
  end

  def destroy
    session[:user_name] = nil
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to new_session_path, notice: 'Successfuly logged out' }
    end
  end

  private

  def authenticate(username)
    User.find_by(username)
  end

  def session_params
    params.require(:session).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_name] = @user.username
        session[:user_id] = @user.id
        format.html { redirect_to user_path(@user.id), notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.attended_events.upcoming
    @past_events = @user.attended_events.past
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(session[:user_id])
  end

  def user_sign_in?
    true if session[:user_id]
  end

  def user_attends?(event)
    true if event.attendees.include?(current_user)
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<p>
  <strong>Upcoming events:</strong>
</p>

<ul id="events">
  <% @upcoming_events.each do |event| %>
    <li>
      <%= link_to event.description, event_path(event.id) %>
      <% unless user_attends?(event) %>
        <%= link_to 'Attend this event', attendance_path(event.id) %>
      <% end %>
    </li>
  <% end %>
</ul>

<p>
  <strong>Past events:</strong>
</p>

<ul id="events">
  <% @past_events.each do |event| %>
    <li>
      <%= link_to event.description, event_path(event.id) %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_field :event_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', user_path(current_user.id) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created_by: <%= @event.creator.username %></strong>
</p>

<p>
  <strong>Attendees:</strong>
</p>

<ul id="attendees">
  <% @event.attendees.all.each do |attendee| %>
    <li>
      <%= attendee.username %>
    </li>
  <% end %>
</ul>
<% unless user_attends?(@event) %>
  <%= link_to 'Attend this event', attendance_path(@event.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <nav class="nav">
  

  <%if session[:user_name]%>
    <p>Welcome<strong><%= session[:user_name] %></strong></p>
    <%= link_to 'Create Event', new_event_path %>
    <%= link_to 'My Events', user_path(session[:user_id]) %>
    <%= link_to 'All Events', events_path %>
    <%= link_to 'Sign out', session_path(session[:user_id]), method: 'delete'%>
  <%else%>
    <%= link_to 'Sign in', new_session_path %>
    <%= link_to 'Sign up', new_user_path %>
  <%end%>
  </nav>
    <div >
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', new_session_path %>

app/views/users/show.html.erb
<% require 'date' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<h2> <%= @user.username %>'s events </h2>
<ul id="events">
  <% @user.created_events.each do |event| %>
    <li>
      <%= link_to event.description, event_path(event.id) %>
    </li>
  <% end %>
</ul>

<h2> Upcoming Events </h2>
<ul id="events">
  <% @upcoming_events.each do |event| %>
      <li>
        <%= link_to event.description, event_path(event.id) %>
      </li>
  <% end %>
</ul>
<h2> Past Events </h2>
<ul id="events">
  <% @past_events.each do |event| %>
      <li>
        <%= link_to event.description, event_path(event.id) %>
      </li>
  <% end %>
</ul>